apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: django
          image: tanmay8898/django
          ports:
            - containerPort: 8080
